project:
  type: website
  output-dir: docs
  resources:
    - assets/**
website:
  title: Owen Tatlonghari Portfolio
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
format:
  html:
    theme: flatly
    css: styles.css
